name: Daily Tests
on:
  schedule:
    # 8am UTC, Mondayâ€“Friday
    - cron: '0 8 * * 1-5'
env:
  NODE_ENV: test
jobs:

  # Run feed tests
  test-feeds:
    name: Run feed tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
        mongodb-version:
          - 4.4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - uses: actions/cache@v1
        env:
          cache-version: v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - run: npm install

      # We cache RSS feed XML for all of the tested feeds, which stops these tests
      # from being quite as brittle
      - uses: actions/cache@v1
        env:
          cache-version: v1
        with:
          path: ./test/feeds/cache
          key: test-feed-cache
          restore-keys: |
            test-feed-cache

      - run: make test-feeds
